### ISSUE TITLE
Recommended way to add 3rd party css framework.

### ISSUE THREAD

**Issue by roylee0704** [bensmithett/webpack-css-example#15]
Hi @bensmithett , first of all, thanks for the blog post and all, it is really really helpful especially for a beginner like me, I've learnt a great deal from what you have written. 

Alright, here's my question, do you have any recommended way to integrate 3rd party css framework like [flexboxgrid](https://goo.gl/imrHBZ), [material-ui](https://goo.gl/G6JrsN), or [boostrap](https://goo.gl/zundla) and etc onto the structure that you've just taught? 

Or it's better to refrain any 3rd party css frameworks from being compiled into a single `bundle.css`?

**Comment by bensmithett** [comment]
Hey @roylee0704!

It depends on the framework & your personal preference, but here's what I'd do:

#### flexboxgrid & bootstrap

flexboxgrid & bootstrap both provide a built CSS file ([flexboxgrid](https://npmcdn.com/flexboxgrid@6.3.0), [bootstrap](https://github.com/twbs/bootstrap/blob/master/dist/css/bootstrap.css)), so if you install it via npm you can just do things exactly the same way:

```es6
import 'flexboxgrid'

const MyFlexboxGrid = React.createClass({
  render () {
    return <div className='container'>...</div>
  }
})

// or...

import 'bootstrap/dist/css/bootstrap.css'

const MyBootstrapThing = React.createClass({
  render () {
    return <div className='some-bootstrap-class'>...</div>
  }
})
```

#### material-ui

material-ui components are all styled via [inline styles](http://material-ui.com/#/customization/inline-styles), so you don't even need to worry about any exported CSS. Just use material-ui components like any other React component.

```es6
import RaisedButton from 'material-ui/lib/raised-button'

const MyAwesomeReactComponent = React.createClass({
  render () {
    return <RaisedButton label="Default" />
  }
})
```
