### ISSUE TITLE
CSS and JS files not found when using file path

### ISSUE THREAD

**Issue by wcsete** [bensmithett/webpack-css-example#18]
If you open up the index via a file:// path, both the CSS and JS are not found. Loading the index with a local server works fine. Since this is a quick example it might be nice to make it work without needed to start a local server.

`GET file:///build/app.css net::ERR_FILE_NOT_FOUND`
`GET file:///build/app.js net::ERR_FILE_NOT_FOUND`

**Comment by bensmithett** [comment]
Fixed by #20
