### ISSUE TITLE
How to convert webpack.config.js to accept .scss instead of .sass?

### ISSUE THREAD

**Issue by her** [bensmithett/webpack-css-example#35]
Hey everyone, 

I really enjoyed Ben's blog post https://www.bensmithett.com/smarter-css-builds-with-webpack/ it's definitely an eye opening change for me and I'm really trying to figure out how to use web pack 

I want to change the example to use .scss and basically use this as a scaffolding. I have a lot to learn but any guidance on how to at least get web pack to succeed in building this would be very much appreciated. 

So far I've tried changing webpack.config.js, by adjusting the loaders. I've also changed the file extensions from .sass to .scss but the build continually failed. I'm getting this error:

`ERROR in ./src/javascripts/footer.js
Module not found: Error: Cannot resolve module 'stylesheets/modules/footer' in /Users/mb/srv/www/webpack-css-example/src/javascripts
 @ ./src/javascripts/footer.js 11:0-37`

I'd have one of these errors for all the respective modules, header, container, and clearfix. 

Any advice? 

Thanks Ben for the great tutorial! 

Thanks everyone

**Comment by her** [comment]
```
{
  test: /\.scss$/,
  loader: ExtractTextPlugin.extract('style-loader', sassLoaders.join('!'))
}
```

This fixed it so I'm closing this issue

**Comment by bensmithett** [comment]
Hey @her (and anyone else who stumbles onto this issue!)

You probably also want to

- remove `indentedSyntax=sass` from [this line](https://github.com/bensmithett/webpack-css-example/blob/master/webpack.config.js#L8)
- add `scss` to the resolved extensions on [this line](https://github.com/bensmithett/webpack-css-example/blob/master/webpack.config.js#L42)

**Comment by her** [comment]
hey thanks @bensmithett 

you're amazing, this helped a lot.

also wanted to say it's *so* cool how you have react in this repository. it's really helpful for someone like me who is just learning. thanks again!
